abbr = {
    "flower": "Flower of Life",
    "plume": "Plume of Death",
    "sands": "Sands of Eon",
    "goblet": "Goblet of Eonothem",
    "circlet": "Circlet of Logos",
    "hp": "HP",
    "hpp": "HP%",
    "atk": "ATK",
    "atkp": "ATK%",
    "def": "DEF",
    "defp": "DEF%",
    "er": "Energy Recharge%",
    "em": "Elemental Mastery",
    "cr": "CRIT Rate%",
    "cd": "CRIT DMG%",
    "pyro": "Pyro DMG Bonus%",
    "electro": "Electro DMG Bonus%",
    "cryo": "Cryo DMG Bonus%",
    "hydro": "Hydro DMG Bonus%",
    "anemo": "Anemo DMG Bonus%",
    "geo": "Geo DMG Bonus%",
    "physical": "Physical DMG Bonus%",
    "healing": "Healing Bonus%"
}

abbr_rev = {
    'Flower of Life': 'flower',
    'Plume of Death': 'plume',
    'Sands of Eon': 'sands',
    'Goblet of Eonothem': 'goblet',
    'Circlet of Logos': 'circlet',
    'HP': 'hp',
    'HP%': 'hpp',
    'ATK': 'atk',
    'ATK%': 'atkp',
    'DEF': 'def',
    'DEF%': 'defp',
    'Energy Recharge%': 'er',
    'Elemental Mastery': 'em',
    'CRIT Rate%': 'cr',
    'CRIT DMG%': 'cd',
    'Pyro DMG Bonus%': 'pyro',
    'Electro DMG Bonus%': 'electro',
    'Cryo DMG Bonus%': 'cryo',
    'Hydro DMG Bonus%': 'hydro',
    'Anemo DMG Bonus%': 'anemo',
    'Geo DMG Bonus%': 'geo',
    'Physical DMG Bonus%': 'physical',
    'Healing Bonus%': 'healing'
}
